language: python
python:
  - "3.6.7"
install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - py.test --cov-config .coveragerc --cov=run   test/
  - coverage report
after_success:
  - coveralls
  - pytest


language: python

python:
- "3.6.4" 

install:
- pip install -r requirements.txt

script:
- pytest --cov=.
- coverage

after_success:
- coveralls
